[package]
name = "lander-bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lander = {path = "../", features = ["wgpu_render"]}
env_logger = "0.9.0"
winit = "0.25.0" 
